# Generated by Django 3.0.5 on 2020-04-06 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50)),
                ('address_line3', models.CharField(blank=True, max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('additional_ph_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '[6-9]\\d{9}'. Up to 10 digits allowed.", regex='^[6-9]\\d{9}$')], verbose_name='additional_phone_number')),
                ('num_fam_mem', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='number_of_family_members')),
                ('google_map_location', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
